### ISSUE TITLE
error when player a is opening the barrel and ad player b destroys the barrel and criticals

### ISSUE THREAD

**Issue by YaNIND** [xSuperr/VanillaBlocks#12]
the eror make server close

**Comment by supercrafter333** [comment]
Please send the error

**Comment by YaNIND** [comment]
[Server thread/CRITICAL]: Error: "Call to a member function getBlockAt() on null" (E
XCEPTION) in "pmsrc/src/pocketmine/tile/Tile" at line 238

**Comment by supercrafter333** [comment]
Please send the COMPLETE error.

**Comment by YaNIND** [comment]
i talk to author not you

**Comment by xSuperr** [comment]
Should be fixed in latest commit if you can test.
