### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by thinh2118** [xSuperr/VanillaBlocks#2]
sometimes used with other vanilla plugins like trident, elytra, firework... it will stop working even though the plugin is still running

**Comment by thinh2118** [comment]
![image](https://user-images.githubusercontent.com/69988685/122650593-0ec73780-d15e-11eb-9198-c4848e6520aa.png)

**Comment by thinh2118** [comment]
![image](https://user-images.githubusercontent.com/69988685/122650605-20a8da80-d15e-11eb-9875-86fa31089104.png)

**Comment by xSuperr** [comment]
I think I know why, can you find one of the plugins that causes this so I can find a fix?

**Comment by YaNIND** [comment]
Not In Vanilla Blocks

**Comment by thinh2118** [comment]
this bug appears when i use plugin in .phar

**Comment by thinh2118** [comment]
I use it with other plugins like trident, firework, vanillaelytra, shield, netherite, jukebox

**Comment by thinh2118** [comment]
You can find it on poggit.

**Comment by xSuperr** [comment]
Should be fixed in version 1.0.2
