### ISSUE TITLE
Wrong Block Facing

### ISSUE THREAD

**Issue by DumbChester** [xSuperr/VanillaBlocks#25]
Sometimes Block would face wrong directions, Eg: StrippedWood should've been placed facing upwards, Which it does for a split second then face sideways after

**Comment by xSuperr** [comment]
Client sided bug, happens with all blocks that have facing states. Same as canceling the block place event, the block still places for a minisecond.

**Comment by DumbChester** [comment]
By sometimes i mean, most of the time, And somehow gets fixed whenever i place it when I'm near placing location, Is there no fix for this?

**Comment by xSuperr** [comment]
Send a video of your problem if possible.

**Comment by DumbChester** [comment]
here you go

https://streamable.com/4f2uk2

**Comment by DumbChester** [comment]
Chance of being flipped wrongly diminishes if I'm near the PlaceBlock Location

**Comment by xSuperr** [comment]
Ah I see, I will fix it when I have time.

**Comment by xSuperr** [comment]
Fixed in version 1.0.7
