### ISSUE TITLE
Lanterns Bug/missed feature 

### ISSUE THREAD

**Issue by DumbChester** [xSuperr/VanillaBlocks#26]
They won't attach to fences when attached from below In Bedrock/Vanilla they can do that.

**Comment by xSuperr** [comment]
They should, unless it's a wall added in my plugin.

**Comment by DumbChester** [comment]
its wooden fence, Wooden fence on top and Lantern Below (Lantern Hanging from below fence) I do this to makenchandeleir Designs in Bedrock, Here it doesn't attach. However it attaches to other full blocks such as logs in a hanging position (Fence below Full Block on top). please look into it.

**Comment by YaNIND** [comment]
I can put it why can't you?

**Comment by DumbChester** [comment]
I wonder why too, I would never open an issue that isn't rue or would help the dev find bugs or improve their work, I could send Vid later if xSuper requested, As i have done before.

Anyway are you sure you have read my Issue? i mean i can place lanterns on top of fences however i cant place it under them, Which i could do on Bedrock.

**Comment by xSuperr** [comment]
Lanterns can be placed under fences correctly? I am going to close this issue, please open another one with a video if you still experience problems.
