### ISSUE TITLE
Can’t place the items

### ISSUE THREAD

**Issue by officialjustine** [xSuperr/VanillaBlocks#3]
I can’t place the barrel, campfire on the ground

**Comment by officialjustine** [comment]
https://user-images.githubusercontent.com/75523106/122673314-6b7c2e00-d202-11eb-883d-f063ecb1ecda.mov

**Comment by xSuperr** [comment]
Do you have any other plugins or spawn protection from pocketmine in that area?

**Comment by officialjustine** [comment]
Yes but I’m Op so I can bypass the protection, I tried also to place away from the spawn same problem

**Comment by xSuperr** [comment]
But do you have any other plugins?

**Comment by officialjustine** [comment]
yes, WorldProtect

**Comment by xSuperr** [comment]
Ok, the latest version from poggit?

**Comment by officialjustine** [comment]
![image](https://user-images.githubusercontent.com/75523106/122676447-c1f06900-d210-11eb-9e16-32b44e76d4b0.png)
I also get this

**Comment by xSuperr** [comment]
Oh, can you update your php version? This plugin is meant for the latest PocketMine, so it's written in php 7.4.

**Comment by officialjustine** [comment]
Ok I'll try on updated PHP

**Comment by officialjustine** [comment]
same problem

**Comment by xSuperr** [comment]
Same error? That error will only happen when PHP is not 7.4.

**Comment by officialjustine** [comment]
Same Problem, I removed the world protect already

**Comment by xSuperr** [comment]
I'll look into it when I get home.

**Comment by xSuperr** [comment]
You have the extened blocks plugin right?

**Comment by officialjustine** [comment]
yes updated from poggit

**Comment by HugoLeBoss91** [comment]
I have the same problem. You want remove VanillaBlock ah this Line: private static VanillaBlocks $instance;
And you must do this for all

**Comment by xSuperr** [comment]
It's because you guys aren't using php 7.4, I will change it when I get home smh

**Comment by xSuperr** [comment]
Should be fixed in version 1.0.2
