### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by MrNinja008** [xSuperr/VanillaBlocks#39]
I am using Latest Version and If i a place any blocks that are implemented with this plugin and then i break a block next to it it becomes updated blocks
![Screenshot_20210716-095752](https://user-images.githubusercontent.com/79526396/125935535-ed84e22a-1e51-4e09-8f6c-4729c215279f.png)
![Screenshot_2021-07-16-15-52-46-229_com mojang minecraftpe](https://user-images.githubusercontent.com/79526396/125935563-1173eb63-85b5-4945-a3e5-f63027f38638.jpg)

**Comment by YaNIND** [comment]
ExtendedBlocks not support AntiXray

**Comment by xSuperr** [comment]
That would probably be the cause of the problem, also it would be AntiXray does not support ExtendedBlocks. @MrNinja008
