### ISSUE TITLE
last pr is bugi

### ISSUE THREAD

**Issue by efor89** [xSuperr/VanillaBlocks#49]
hi this error is in the last pr.

 Error: "Class "xSuper\VanillaBlocks\blocks\Facing" not found" (EXCEPTION) in "plugins/VanillaBlocks_dev-31.phar/src/xSuper/VanillaBlocks/blocks/BarrelBlock" at line 51

**Comment by xSuperr** [comment]
Then just don't use that version lol

**Comment by efor89** [comment]
wtf i dont use this version i say it to you that you can fix it rotfl

**Comment by efor89** [comment]
sry that i try to help you
