### ISSUE TITLE
Cant Have Campfire

### ISSUE THREAD

**Issue by thinh2118** [xSuperr/VanillaBlocks#5]
![image](https://user-images.githubusercontent.com/69988685/122860656-51e4fe80-d348-11eb-93d8-ab60d27c133a.png)

**Comment by YaNIND** [comment]
register the blocks in VanillaBlocks.php

**Comment by xSuperr** [comment]
Yeah I see that, I was testing adding the campfire item in and not registering it in the creative inventory. Its fixed in the latest commit.
